spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hexa?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a03290907!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: create

logging:
  level:
    org:
      hibernate:
        sql : debug
        type : trace